### ISSUE TITLE
api throw "network" error when in Electron env

### ISSUE THREAD

**Issue by ATKovz** [WICG/speech-api#80]
it works success in browser env, but when I use it in electron, it throw 
![image](https://user-images.githubusercontent.com/38774172/86761709-bc8a2500-c078-11ea-8a42-3ef66c9e7167.png) this error instantly

env: both macos / win10 electron 9.0.0

**Comment by foolip** [comment]
@ATKovz while I have not tried it myself, I would guess that speech recognition doesn't work by default in Electron, since you need an API key for Google's speech recognition cloud service. https://github.com/electron/electron/issues/8810 suggests that https://www.electronjs.org/docs/api/environment-variables#google_api_key might be the way to do this, but again I haven't tried it.

This repository is for the specification itself, and not for implementations of the API.

I would recommend following https://github.com/electron/electron/issues/24278, which seems to be the most recent issue about this in Electron.
