### ISSUE TITLE
Web Speech Api not working on chinese network

### ISSUE THREAD

**Issue by svecchi-brochesia** [WICG/speech-api#83]
Hi, we have a problem with our WebSpeech API solution on chrome with a Chinese Client. The speech recognizing start but not give us a result. Only work with VPN (because google server are blocked in China). We would like to make available our solution without VPN in Chrome. There's a solution for this problem?

**Comment by foolip** [comment]
Hi @svecchi-brochesia! It sounds like this is an issue with Google Chrome. I've searched our bug tracker but can't find any existing reports about this. I suspect it will not be possible to fix, but perhaps it could fail in a more clear manner. If this still affects you, would you mind filing an issue at https://bugs.chromium.org/p/chromium/issues/entry?

I'll go ahead and close this issue since this is about the spec, not a specific browser.
